### ISSUE TITLE
Links without locale & branch are broken

### ISSUE THREAD

**Issue by MichaelDeBoey** [remix-run/react-router-website#123]
https://reactrouter.com/start/concepts used to redirect to https://reactrouter.com/en/main/start/concepts, but this doesn't seem to work anymore

We use these in several of the Remix docs, so all these links are now broken

**Comment by brophdawg11** [comment]
We removed this "version-less" redirect because it was prone to breaking across major releases.  For example, when we remove `json` in v7, https://reactrouter.com/fetch/json would have started to 404 because the links will always redirect to the latest version and v7 doesn't have that API.  Instead, we need to always include _some_ known good version for these links - so we moved to a format of https://reactrouter.com/v6/fetch/json which will redirect to the latest in the v6 release line.

We need to go fix some of these old types of links - I did a handful for RR in https://github.com/remix-run/react-router/pull/12141 and have some local changes for the Remix repo as well that I'll get pushed shortly and will drop a link here too.  If you see others that aren't in the source code please let us know!

**Comment by brophdawg11** [comment]
Remix PR https://github.com/remix-run/remix/pull/10130
