### ISSUE TITLE
Bug: Links in "On this page" screwed up the style

### ISSUE THREAD

**Issue by QzCurious** [remix-run/react-router-website#139]
https://github.com/user-attachments/assets/b41740c8-6e17-40dc-a16f-ddce298e9ac4

**Comment by brookslybrand** [comment]
Thanks @QzCurious, I thought I'd fixed this on Friday, but evidently didn't. It's has been fixed now

The underlying issue is [a bug in react-router](https://github.com/remix-run/react-router/issues/12382), which as far as I can tell has existed for _a long time_. I'm surprised it took us this long to find it, but I'm glad we did

Sorry to you and anyone else dealing with a buggy website over the weekend!
