### ISSUE TITLE
Tutorial: confirm in contact.jsx

### ISSUE THREAD

**Issue by kevinjaygonz** [remix-run/react-router-website#71]
I was receiving an error stating "Unexpected use of 'confirm'"
![image](https://github.com/remix-run/react-router-website/assets/13715369/ee1d5de4-8c36-491e-a214-663214cbbb55)

I was able to resolve this by adding `window.confirm` instead of just `confirm`
![image](https://github.com/remix-run/react-router-website/assets/13715369/c7dbbf93-57f4-4394-81b2-74d4e1e95938)

**Comment by brookslybrand** [comment]
@kevinjaygonz weird, I haven't run into this. If you'd like to open up a PR to the docs you can do so [in remix-run/remix](https://github.com/remix-run/remix/blob/7c0366fc73e513f55fe643291d1b5669d62ad13d/docs/start/tutorial.md?plain=1#L220-L222).

I'm going to go ahead and close this issue since it does not apply to this repo
